server:
  port: 8080
  context-path: /kiss/manage

spring:
  redis:
    database: 0
    host: 192.168.1.12
    port: 6379
    password: zjtachao
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 100
      min-idle: 1

  datasource:
    url: jdbc:mysql://192.168.1.11:3306/fish?useUnicode=true&characterEncoding=UTF-8
    username: zjtachao
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 50

mybatis:
  type-aliases-package: com.zjtachao.fish
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


com:
  zjtachao:
    fish:
      kiss:
        manage:
          normal:
            user:
              role:
                admin: admin
            param:
              min-date: 201801
              goods: "[{\"goodsName\":\"舒适放松\" , \"goodsPrice\":10.00 , \"goodsUnit\": 10.00 , \"goodsOrder\": 1} , {\"goodsName\":\"疲劳恢复\" , \"goodsPrice\":15.00 , \"goodsUnit\": 20.00 , \"goodsOrder\": 2} ,{\"goodsName\":\"酸痛改善\" , \"goodsPrice\":20.00 , \"goodsUnit\": 30.00 , \"goodsOrder\": 3}]"
          redis:
            param:
              area:
                province: kiss:param:area:province-all-list
                city-all: kiss:param:area:city-all-list
                city: kiss:param:area:city-
                county-all: kiss:param:area:county-all-list
                county: kiss:param:area:county-